### ISSUE TITLE
Fix for 0c8 No app name specified

### ISSUE THREAD

**Issue by Tribalize** [fjies/dashboard#110]
If downloaded from master. and try to install  you get error
No app name specified

Which can be fixed by renaming the app folder to ocdashboard

**Comment by fjies** [comment]
Yes the master branch is currently the "old" 1.3.2 with name ocdashboard.
The version 2 branch is the new (beta) 1.6 version.

I will change that in a correct structure later on.

**Comment by fjies** [comment]
is changed
