### ISSUE TITLE
php 5.3.8 support breaking, due array usage

### ISSUE THREAD

**Issue by mckaygerhard** [fjies/dashboard#114]
with lasted i got :

´´´
PHP Parse error:  syntax error, unexpected '[', expecting ')' in /var/www/simplenet/apps/dashboard/appinfo/app.php on line 19

´´´

due u have and array as ['id' =>'element'] event array('id'=>'element') in app.php

**Comment by fjies** [comment]
this was generated by the startup command line tools

**Comment by mckaygerhard** [comment]
ah? how that? i see that in app.php, this file its generated?

**Comment by fjies** [comment]
generated with the app developer startup tool.

As in the ready written, you need at least php 5.4.

**Comment by mckaygerhard** [comment]
please, can u made something for generation support for php 5.3, if this will left as its, this app could not be installed in stable servers with debian and redhat linux, u lost important targets!

**Comment by fjies** [comment]
well, I have to look at that specially. I'm using php 5.4 because that is the new dependency for oc8.
That will take some time, because I will first try to fix some other bugs.

**Comment by fjies** [comment]
is the app runable in php 5.3 with this one change?

**Comment by mckaygerhard** [comment]
wait for me a 15 minutes and i confirm (well reconfirm) at least the local runnig widgets...

**Comment by fjies** [comment]
thanks for your help, I have to go sleeping now, I'll have a long day tomorrow.
I guess, I will go on on friday.

**Comment by mckaygerhard** [comment]
how can i disable mail widget, i not have configured yet in the testing server? when added mail widget i cannot display more .. until that i tested activity, clock, bookmarks, weather.

**Comment by mckaygerhard** [comment]
i can confirm now works perfectly in oc7 with php 5.3.8, mail cannot test (too lazy to configure internal mail), i see that if user enable a bad configured widget cannot added more...

**Comment by mckaygerhard** [comment]
commit the pull to close the issue

**Comment by fjies** [comment]
merged
