### ISSUE TITLE
verify availability for weather, widget crash and could not added more

### ISSUE THREAD

**Issue by mckaygerhard** [fjies/dashboard#118]
must put a conditional for weather widget if could not retrieve data..

when couldnt retreivbe data widget does not display and cannot permit added more widgets to the dashboard..

log:
```
{"reqId":"5502f7f8db562","app":"dashboard","message":"could not fetch weather data (url=http:\/\/api.openweathermap.org\/data\/2.5\/weather?q=Berlin&lang=es&units=metric)","level":0,"time":"2015-03-13T14:45:44+00:00","method":"POST","url":"\/simplenet\/index.php\/apps\/dashboard\/widget\/complete"}
```

the problem its in the fechContent function, curl its called syncroneos, must made a asincroneus-like call

my idea:

separate the function, fechcontent into two: "fecthContent" and "wgetContent", 

in the wgetContent, launch the process to background and dump response to a file, no wait for return data

in the fechtContent launch a loop for get dta from funtion, (inside revise the file), if not return data (file still does not exits) pain a empty widget

**Comment by fjies** [comment]
still available with version 1.6.2?

**Comment by mckaygerhard** [comment]
unnecessary, it would not help, i see the commits, the problems still persist due u only reduces the time of wait reponse, but still need the reponse.. 

i think the problem are that widget need a response.. so here are the 3 seconds of wait of curls, the second of all code operations "exec curl, with for response, got a response, analise timeout".. u got it? in my vsion, i think sending the operation to background but i not have the knowledge right now for code that!

around of nomenber i'll got more in oc development due now i very busy with others projects.. but i can help a little but right now i cannot.

**Comment by mckaygerhard** [comment]
i'll will be more close to the commits u made and help to solve in the next version but please u will mantain a backguard compatibility with oc 7.X releases and php 5.3?

i can help a lot but i need php 5.3 and oc 7.X compatibility help also., so ill close this issue and in a few monts i'll help but only for oc 7 and php 5.3 exclusivlelly if that
