### ISSUE TITLE
ibrary xml with a version higher than 1.2 is required - available version 0.0.0.0.

### ISSUE THREAD

**Issue by mtk64** [fjies/dashboard#120]
Hello Florian 
i just upgraded to OC 8 and i can see Dashboard 1.6.0beta within the deactivated apps but cannot activate because of this here: 

The dashboard app presents you quick and smart information.

Die App kann nicht installiert werden, weil die folgenden Abhängigkeiten nicht erfüllt sind:

    Library xml with a version higher than 1.2 is required - available version 0.0.0.0.

Before I do some stupid stuff please instruct me if I have to do something or if this is just an issue.
Don't know it ... Which library do i have to install?
kind regards
Michael

**Comment by fjies** [comment]
Hello,
you always need a xml package.
I don't know which version is minimum needed.
The dashboard app has no specific requirements belong xml.

Can you activate other apps?
Are there log entrys in the php error log?

**Comment by mckaygerhard** [comment]
this problem its related to a php installed, seem that the php does not have some xml parsing capabilities..

**Comment by Thomanji** [comment]
Did you find an actual solution for this? I have the same error and I have the latest xml package installed. I run CentOS 6.6 with PHP5.4
Here are the packages I have on there:
libxml2 2.7.6-17.el6_6.1
php54-xml 5.4.16-1.ius.el6
php54-xmlrpc 5.4.16-1.ius.el6
xml-common 0.6.3-33.el6

I did search trough YUM but I do not find anything that would be relevant. Therefore, I would be happy to share if you found a solution.

**Comment by mckaygerhard** [comment]
well in my case i used debian derivate VenenuX that have never that problem.. seems that the php reported version are wrong, its hard to reproduce to me due i not used windo-like distributions.. either recent releases ...

**Comment by mtk64** [comment]
Meanwhile i use Dashboard 1.6.2 and this is working fine.
Dashboard 1.6.0beta is still not activateable, so I will delete it from filessystem.
