### ISSUE TITLE
Problems with Weather Widget

### ISSUE THREAD

**Issue by juergeneberhardt** [fjies/dashboard#121]
Good evening, 

I added some widgets: clock, mail, tasks. It worked well but for a while.  
After adding the weather widget, the shown widgets were random. Sometimes only the clock appears , sometimes even nothing appears. 
After a long time waiting, the widgets appears one after another but in different order every time.
The weather widget is not updating any more. 
I do not know if the weather widget is responsible for this behaviour.
Removing it does not help. The app is very slow. 

I have tested Dashboard version 1.6.1 and 1.6.2 on Owncloud 8.0.2 
PHP-Version: 5.4.39
OS: Debian wheezy 

Regards and thank you

Jürgen Eberhardt

**Comment by juergeneberhardt** [comment]
Oh, I have forgotten one more: there is no entry in the log-file about Dashboard

**Comment by fjies** [comment]
belongs to #118

**Comment by fjies** [comment]
please try new version of dashboard 1.6.2.
