### ISSUE TITLE
Dashboard does not work (with any widget) --> Call to a member function getHtml() on a non-object at /var/www/owncloud/apps/dashboard/controller/widgetcontroller.php#64

### ISSUE THREAD

**Issue by flipsa** [fjies/dashboard#122]
Hello,

I'm trying to run the latest dashboard version (1.6.2 / git checkout from today). I was using dashboard in previous OC version (6/7), but did a clean re-install: deactivated in apps, deleted from apps dir, deleted oc_dashboard_config and oc_dashboard_used_hashs in mySQL; then git checkout, activated it in apps. 

Problem:
After trying to add a widget it displays fine, but if I navigate away (say to the "files" app) and come back to dashboard, all i get is an eternally spinning wheel / loading gif, but no widget shows up (i tried "activity", "weather", "bitcoin", etc). 

OC log shows this:

    Error	PHP	Call to a member function getHtml() on a non-object at /var/www/owncloud/apps/dashboard/controller/widgetcontroller.php#64

I tried everything i could think of: reinstall, delete tables, adding one by one, adding some at the same time, etc - but no success. Here's some info on my setup (everything runs on an ARM7 SoC):

Dashboard Version:

    user@udoo:~$ cat dashboard/appinfo/info.xml
    [...]
    <version>1.6.2</version>
    [...]

OC Version:

    user@udoo:~$ cat ../version.php 
    <?php 
    $OC_Version = array(8,0,2,0);
    $OC_VersionString = '8.0.2';
    $OC_Channel = 'stable';
    $OC_Build = '2015-03-09T13:29:12+00:00 8db687a1cddd13c2a6fb6b16038d20275bd31e17';OC 8.0.2 

mySQL Version:

    user@udoo:~$ mysql --version
    mySQL Ver 14.14 Distrib 5.5.41, for debian-linux-gnu (armv7l) using readline 6.3

PHP Version:

    user@udoo:~$ php --version
    PHP 5.5.9-1ubuntu4.7 (cli) (built: Mar 16 2015 21:22:15) 
    Copyright (c) 1997-2014 The PHP Group
    Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
        with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

Thanks for any help! Let me know in case you need more info...

**Comment by mckaygerhard** [comment]
hey seems the problem was a change in oc 8.X releases, do u said that in oc 6 and oc7 works well, but when installed in oc 8.x got crash!? so the problem was there! 

well ocdashboard now must be revised to try oc new api, wheantime u must use oc7 or oc6, i'm not a fan of making updates, if some thing was working and work, let it as is

**Comment by fjies** [comment]
hi, try the new version 1.6.2.

**Comment by flipsa** [comment]
Seems to work fine now, after completely uninstalling (and deleting all db tables and the references to the app in the table oc_appconfig) & reinstalling the 1.6.2 version. Thanks!
