### ISSUE TITLE
OC 8.1 support?

### ISSUE THREAD

**Issue by jperville** [fjies/dashboard#125]
After browsing the code, the maximum supported ownCloud version is 8.0.5 as of current master). What would be needed to add owncloud 8.1 compatibility?

**Comment by srt10coupe** [comment]
root
cd /var/www/owncloud/
su www-data
PHP occ app:enable dashboard

can the 'modest so far' app enjoy. :)

**Comment by jperville** [comment]
Hi @srt10coupe , I was not precise enough:
 - the last officially released version (1.6.1) works with oc 8.1 (because no requiremax is specified in appinfo/info.xml) however it does not support postgres (that version was released on 7th March while postgres support was merged to master around 9th March)
 - the current master head supports postgres but does not support oc 8.1 anymore because a [requiremax 8.0.5](https://github.com/fjies/dashboard/blob/07f45185e35b74a9fc073c4e1c2bfc1102e08c1e/appinfo/info.xml#L10) directive was added at some point.

As a workaround, I have found an older changeset which supports postgres and does not exclude oc 8.1 in its appinfo/info.xml : https://github.com/fjies/dashboard/commit/0a3db7f1f4343a6c833ba3de3ac9ad044effdeff 

I will use my workaround for the moment however it would be nice to restore oc 8.1 compatibility in the appinfo/info.xml so that github users can test it with the latest stable version.

**Comment by fjies** [comment]
hi, and thanks for the question and help.
I published a few seconds ago the version 1.6.2.
This should work for oc8.1.
(Please try and report...)

**Comment by srt10coupe** [comment]
i love this app! the best app for owncloud!

**Comment by srt10coupe** [comment]
8.1.* support thx.

my config.php

'defaultapp' => 'dashboard',

**Comment by srt10coupe** [comment]
add 2 bookmarks widgets site won't load more.

**Comment by jperville** [comment]
Works like a charm, thank you @fjies
